export const CORPORATE_ENEMY_TYPES = [
  'tiktok',
  'youtube',
  'chatgpt',
  'discord',
  'google',
  'wikipedia',
  'gmail',
  'instagram',
  'facebook',
  'linkedin',
  'teams',
  'whatsapp',
  'twitter',
];
export const MAX_CORPORATE_ENEMIES = 132;

const sharedPressureDamage = {
  damagePressure: 0.067,
  spawnWeight: 1,
};

export const CORPORATE_ENEMY_PROFILES = {
  tiktok: {
    ...sharedPressureDamage,
    type: 'tiktok',
    label: 'TikTok',
    textureKey: 'logo_tiktok',
    asset: 'corporate/tiktok.svg',
    primaryPattern: 'viral-sweep',
    strategies: ['sweeper', 'zigzag', 'cutoff'],
    damageBase: 12.2,
    damagePressure: 0.066,
    size: 54,
    bodySize: 86,
    jitter: 0.58,
    retargetBaseMs: 600,
    retargetPressureMs: 6.2,
    lungeMinMs: 640,
    lungeBaseMinMs: 1300,
    lungeBaseMaxMs: 2500,
    lungePressureMs: 8.4,
    pulseScale: 1.18,
    pulseMs: 410,
    color: 0x00f2ea,
  },
  youtube: {
    ...sharedPressureDamage,
    type: 'youtube',
    label: 'YouTube',
    textureKey: 'logo_youtube',
    asset: 'corporate/youtube.svg',
    primaryPattern: 'recommendation-cutoff',
    strategies: ['cutoff', 'herder', 'ambusher'],
    damageBase: 12.8,
    damagePressure: 0.071,
    size: 62,
    bodySize: 92,
    jitter: 0.36,
    retargetBaseMs: 820,
    retargetPressureMs: 4.8,
    lungeMinMs: 820,
    lungeBaseMinMs: 1800,
    lungeBaseMaxMs: 3100,
    lungePressureMs: 7.2,
    pulseScale: 1.12,
    pulseMs: 620,
    color: 0xff0033,
  },
  chatgpt: {
    ...sharedPressureDamage,
    type: 'chatgpt',
    label: 'ChatGPT',
    textureKey: 'logo_chatgpt',
    asset: 'corporate/chatgpt.svg',
    primaryPattern: 'predictive-ambush',
    strategies: ['predictor', 'ambusher', 'mirror'],
    damageBase: 11.9,
    damagePressure: 0.069,
    size: 58,
    bodySize: 88,
    jitter: 0.24,
    retargetBaseMs: 760,
    retargetPressureMs: 5.6,
    lungeMinMs: 740,
    lungeBaseMinMs: 1500,
    lungeBaseMaxMs: 2800,
    lungePressureMs: 7.8,
    pulseScale: 1.15,
    pulseMs: 540,
    color: 0x10a37f,
  },
  discord: {
    ...sharedPressureDamage,
    type: 'discord',
    label: 'Discord',
    textureKey: 'logo_discord',
    asset: 'corporate/discord.svg',
    primaryPattern: 'server-swarm-orbit',
    strategies: ['orbiter', 'flanker', 'pack'],
    damageBase: 11.6,
    damagePressure: 0.064,
    size: 56,
    bodySize: 88,
    jitter: 0.46,
    retargetBaseMs: 700,
    retargetPressureMs: 5.8,
    lungeMinMs: 700,
    lungeBaseMinMs: 1600,
    lungeBaseMaxMs: 2900,
    lungePressureMs: 7.4,
    pulseScale: 1.2,
    pulseMs: 500,
    color: 0x5865f2,
  },
  google: {
    ...sharedPressureDamage,
    type: 'google',
    label: 'Google',
    textureKey: 'logo_google',
    asset: 'corporate/google.svg',
    primaryPattern: 'search-grid-crawler',
    strategies: ['search-crawler', 'rank-cutoff', 'map-pin'],
    damageBase: 11.8,
    size: 60,
    bodySize: 90,
    jitter: 0.3,
    retargetBaseMs: 680,
    retargetPressureMs: 5.9,
    lungeMinMs: 720,
    lungeBaseMinMs: 1450,
    lungeBaseMaxMs: 2750,
    lungePressureMs: 7.6,
    pulseScale: 1.13,
    pulseMs: 560,
    color: 0x4285f4,
  },
  wikipedia: {
    ...sharedPressureDamage,
    type: 'wikipedia',
    label: 'Wikipedia',
    textureKey: 'logo_wikipedia',
    asset: 'corporate/wikipedia.svg',
    primaryPattern: 'citation-web-cage',
    strategies: ['citation-web', 'archive-cage', 'knowledge-orbit'],
    damageBase: 11.2,
    size: 60,
    bodySize: 88,
    jitter: 0.2,
    retargetBaseMs: 980,
    retargetPressureMs: 4.1,
    lungeMinMs: 920,
    lungeBaseMinMs: 2000,
    lungeBaseMaxMs: 3400,
    lungePressureMs: 6.2,
    pulseScale: 1.09,
    pulseMs: 720,
    color: 0xf2f2f2,
  },
  gmail: {
    ...sharedPressureDamage,
    type: 'gmail',
    label: 'Gmail',
    textureKey: 'logo_gmail',
    asset: 'corporate/gmail.svg',
    primaryPattern: 'inbox-pincer',
    strategies: ['inbox-pincer', 'reply-all-flank', 'spam-filter'],
    damageBase: 12.1,
    size: 60,
    bodySize: 90,
    jitter: 0.34,
    retargetBaseMs: 720,
    retargetPressureMs: 5.4,
    lungeMinMs: 720,
    lungeBaseMinMs: 1500,
    lungeBaseMaxMs: 2800,
    lungePressureMs: 7.5,
    pulseScale: 1.14,
    pulseMs: 520,
    color: 0xea4335,
  },
  instagram: {
    ...sharedPressureDamage,
    type: 'instagram',
    label: 'Instagram',
    textureKey: 'logo_instagram',
    asset: 'corporate/instagram.svg',
    primaryPattern: 'story-ring-loop',
    strategies: ['story-ring', 'reels-zigzag', 'influencer-herd'],
    damageBase: 12.0,
    size: 58,
    bodySize: 88,
    jitter: 0.52,
    retargetBaseMs: 620,
    retargetPressureMs: 6.1,
    lungeMinMs: 680,
    lungeBaseMinMs: 1350,
    lungeBaseMaxMs: 2600,
    lungePressureMs: 8.2,
    pulseScale: 1.2,
    pulseMs: 450,
    color: 0xe1306c,
  },
  facebook: {
    ...sharedPressureDamage,
    type: 'facebook',
    label: 'Facebook',
    textureKey: 'logo_facebook',
    asset: 'corporate/facebook.svg',
    primaryPattern: 'feed-herd-memory',
    strategies: ['feed-herd', 'friend-request-pack', 'memory-ambush'],
    damageBase: 11.7,
    size: 58,
    bodySize: 88,
    jitter: 0.42,
    retargetBaseMs: 760,
    retargetPressureMs: 5.1,
    lungeMinMs: 760,
    lungeBaseMinMs: 1600,
    lungeBaseMaxMs: 3000,
    lungePressureMs: 7,
    pulseScale: 1.16,
    pulseMs: 560,
    color: 0x1877f2,
  },
  linkedin: {
    ...sharedPressureDamage,
    type: 'linkedin',
    label: 'LinkedIn',
    textureKey: 'logo_linkedin',
    asset: 'corporate/linkedin.svg',
    primaryPattern: 'career-ladder-network',
    strategies: ['career-ladder', 'recruiter-cutoff', 'network-flank'],
    damageBase: 11.4,
    size: 58,
    bodySize: 88,
    jitter: 0.28,
    retargetBaseMs: 860,
    retargetPressureMs: 4.6,
    lungeMinMs: 840,
    lungeBaseMinMs: 1800,
    lungeBaseMaxMs: 3200,
    lungePressureMs: 6.8,
    pulseScale: 1.1,
    pulseMs: 680,
    color: 0x0a66c2,
  },
  teams: {
    ...sharedPressureDamage,
    type: 'teams',
    label: 'Teams',
    textureKey: 'logo_teams',
    asset: 'corporate/teams.svg',
    primaryPattern: 'meeting-gridlock',
    strategies: ['meeting-gridlock', 'calendar-block', 'status-mirror'],
    damageBase: 11.9,
    size: 60,
    bodySize: 90,
    jitter: 0.22,
    retargetBaseMs: 900,
    retargetPressureMs: 4.4,
    lungeMinMs: 880,
    lungeBaseMinMs: 1900,
    lungeBaseMaxMs: 3300,
    lungePressureMs: 6.5,
    pulseScale: 1.11,
    pulseMs: 700,
    color: 0x6264a7,
  },
  whatsapp: {
    ...sharedPressureDamage,
    type: 'whatsapp',
    label: 'WhatsApp',
    textureKey: 'logo_whatsapp',
    asset: 'corporate/whatsapp.svg',
    primaryPattern: 'message-bounce-doubletick',
    strategies: ['message-bounce', 'group-chat-pack', 'double-tick'],
    damageBase: 11.6,
    size: 58,
    bodySize: 88,
    jitter: 0.5,
    retargetBaseMs: 640,
    retargetPressureMs: 5.9,
    lungeMinMs: 680,
    lungeBaseMinMs: 1400,
    lungeBaseMaxMs: 2700,
    lungePressureMs: 7.9,
    pulseScale: 1.18,
    pulseMs: 490,
    color: 0x25d366,
  },
  twitter: {
    ...sharedPressureDamage,
    type: 'twitter',
    label: 'Twitter',
    textureKey: 'logo_twitter',
    asset: 'corporate/twitter.svg',
    primaryPattern: 'doomscroll-dive-trend',
    strategies: ['doomscroll-dive', 'quote-retweet-cutoff', 'trend-sweep'],
    damageBase: 11.8,
    size: 58,
    bodySize: 88,
    jitter: 0.54,
    retargetBaseMs: 590,
    retargetPressureMs: 6.3,
    lungeMinMs: 650,
    lungeBaseMinMs: 1300,
    lungeBaseMaxMs: 2550,
    lungePressureMs: 8.5,
    pulseScale: 1.19,
    pulseMs: 430,
    color: 0x1da1f2,
  },
};

function clamp01(value) {
  if (!Number.isFinite(value)) return 0;
  return Math.min(0.999999999999, Math.max(0, value));
}

function randomIndex(length, rng) {
  return Math.floor(clamp01(rng()) * length);
}

export function getCorporateEnemyProfile(type) {
  const profile = CORPORATE_ENEMY_PROFILES[type];
  if (!profile) throw new Error(`Unknown corporate enemy type: ${type}`);
  return profile;
}

export function pickCorporateEnemyType(rng = Math.random) {
  const total = CORPORATE_ENEMY_TYPES.reduce((sum, type) => sum + getCorporateEnemyProfile(type).spawnWeight, 0);
  let roll = clamp01(rng()) * total;
  for (const type of CORPORATE_ENEMY_TYPES) {
    roll -= getCorporateEnemyProfile(type).spawnWeight;
    if (roll < 0) return type;
  }
  return CORPORATE_ENEMY_TYPES.at(-1);
}

export function getCorporateStrategy(profileOrType, rng = Math.random) {
  const profile = typeof profileOrType === 'string' ? getCorporateEnemyProfile(profileOrType) : profileOrType;
  return profile.strategies[randomIndex(profile.strategies.length, rng)];
}

export function getTargetCorporateEnemyCount({ score = 0, survivalTime = 0 } = {}) {
  const safeScore = Math.max(0, Number.isFinite(score) ? score : 0);
  const safeSurvivalTime = Math.max(0, Number.isFinite(survivalTime) ? survivalTime : 0);
  return Math.min(MAX_CORPORATE_ENEMIES, 9 + Math.floor(safeScore / 4) + Math.floor(safeSurvivalTime / 9));
}
